### PR TITLE
Adding TestNG setup configuration

### PR DESCRIPTION
**Pull request by bhargavkumar-65**
Hi Playwright Team,
In this PR i have added TestNG setup configuration without Parallel run config.
Currently testing the TestFixtures setup with parallel runs and will raise PR accordingly.

### CODE REVIEW

**Review by mxschmitt — COMMENTED** [review]
We generate these mdx files, the source is here: https://github.com/microsoft/playwright/blob/main/docs/src/test-runners-java.md

**Comment by bhargavkumar-65** [comment]
> We generate these mdx files, the source is here: https://github.com/microsoft/playwright/blob/main/docs/src/test-runners-java.md

@mxschmitt yes i can see the mdx file for Junit, added the configuration for TestNG testRunner as TestNG is one of the popular framework

**Comment by mxschmitt** [comment]
We don't make content changes in this repository. If you want to contribute to the documentation, you need to create a pull request against the playwright repository and against this file: https://github.com/microsoft/playwright/blob/main/docs/src/test-runners-java.md

**Comment by bhargavkumar-65** [comment]
> We don't make content changes in this repository. If you want to contribute to the documentation, you need to create a pull request against the playwright repository and against this file: https://github.com/microsoft/playwright/blob/main/docs/src/test-runners-java.md
i am a bit lost, can you please provie more info on where to create a PR, this PR is under palaywright.dev against this file: https://github.com/microsoft/playwright/blob/main/docs/src/test-runners-java.md

**Comment by mxschmitt** [comment]
You need to create a PR inside microsoft/playwright and modify this file: https://github.com/microsoft/playwright/blob/main/docs/src/test-runners-java.md

You then can close this PR.

**Comment by bhargavkumar-65** [comment]
Understood, closing this PR. thankyou @mxschmitt

**Pull request closed without merging**
