### PR TITLE
workflow example fix

### PR DESCRIPTION
**Pull request by krutoo**
GitHub Actions workflow file example fix

### CODE REVIEW

**Comment by mxschmitt** [comment]
As per github pull request template:

  The actual source of the file which you are probably editing lives in this repository
  https://github.com/microsoft/playwright/blob/main/docs
  Thank you for doing the Pull Request there!

**Comment by krutoo** [comment]
@mxschmitt im new in open source contributions) should i do something else?

**Comment by mxschmitt** [comment]
You should close this PR and open a PR in the microsoft/playwright repository instead. You need to modify this file:

https://github.com/microsoft/playwright/blob/main/docs/src/ci.md

**Comment by mxschmitt** [comment]
Closing as per above, happy to review a PR in the right repo.

**Pull request closed without merging**
