### PR TITLE
Fix GitHub casing in title

### PR DESCRIPTION
**Pull request by karlhorky**
First of all, thanks for Playwright! 🙌 Great tool :)

Fix the casing of GitHub (small `h` -> large `H`) in 3 places on the page (also page title)

Screen Shot 2022-10-05 at 12 39 19

### CODE REVIEW

**Comment by karlhorky** [comment]
Oh I just read the comment in the issue above - apparently I'm supposed to do a PR over at  https://github.com/microsoft/playwright/tree/main/docs/src ?

**Comment by karlhorky** [comment]
Interesting, looks like the file over there has been updated already: by @ushuz in https://github.com/microsoft/playwright/pull/17418 🤔

And the file locally has been updated? (https://github.com/microsoft/playwright.dev/blob/main/nodejs/docs/ci-intro.mdx)  But not the `latest-docs` version?

**Comment by karlhorky** [comment]
Hm, not sure I understand why it's like this, but I guess this PR can be closed now?

**Comment by mxschmitt** [comment]
This is already fixed and gets released in the next stable version. If you press tab 5 times, you'll see the next docs version.

**Comment by karlhorky** [comment]
Ok thanks for the heads up. When do stable versions get released, on average?

> If you press tab 5 times, you'll see the next docs version.

Oh this is cool! I can't reproduce it though - I tried on https://playwright.dev and https://playwright.dev/docs/intro and all tabbing did was change the focused element.

**Comment by mxschmitt** [comment]
Ah I meant shift! See here: https://playwright.dev/docs/next/ci-intro

Usually we release every month.

**Comment by karlhorky** [comment]
> Ah I meant shift

fancy trick! I'll try to remember this!

**Pull request closed without merging**
